### PR TITLE
fix: rename user key placeholder

### PR DESCRIPTION
**Pull request by mkorszun**
customer might not know what 3scale is...

### CODE REVIEW

**Comment by spier** [comment]
@msuess I agree with @mkorszun that the customers will not know what 3scale is. However I don't know if they will understand what "User Key" is either. So I am not sure what to do here.

**Comment by msuess** [comment]
Maybe "Key from API portal"?

**Comment by spier** [comment]
We call it "developer portal" rather than "API portal".

Could we somehow indicate that all of the 3 values (user-key, client_id, client_secret) come from the developer portal? Like group them together somehow? Or would that be misleading?

**Comment by msuess** [comment]
Maybe more specific, HOWTO-like instructions in the README/dev portal could solve this. I can't come up with a nice UX that could fix this right now.

**Comment by msuess** [comment]
UX idea: put little question marks next to the inputs and show a tooltip on click that explains where to get these values from (preferably with pictures)

**Comment by spier** [comment]
For now, let's actually go with "User Key", as Mateusz suggested. I think that is at least a bit better.
And the customers that want to use this will have to have developer portal access anyways.

Can you also take a new screenshot for the README when you merge this?

**Comment by spier** [comment]
Btw I learnt the trick from Niall: Dragging and dropping a picture into the comments here will automatically upload this and give you a URL that you can use in the readme. Did not know that :)

**Comment by msuess** [comment]
Hah, I was wondering how you did that without adding the picture to the repo

**Pull request closed without merging**
